adminUser:
  password: vault:lordlemon/adminUser:password
  username: admin
dashboardAuthID: vault:lordlemon:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:lordlemon:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:lordlemon/pipelineUser:token
  username: arcalos-bot
prow:
  hmacToken: vault:lordlemon/prow:hmacToken
parentDomain: jxaas.dev
parentProject: arcalos-domain-name
parentDNSZone: jxaas-dev-parent
tenantServiceDBInstance: "arcalos-tenant-service-db:us-east1:jx-tenant-db=tcp:5432"
